name: 'Setup Node.js and pnpm'
description: 'Composite action to setup Node.js and pnpm with optional dependency installation'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '8'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  frozen:
    description: 'Use frozen lockfile for install'
    required: false
    default: 'true'
  registry-url:
    description: 'Optional registry URL for Node.js setup'
    required: false
    default: ''
  cache:
    description: 'Enable pnpm cache'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js (with cache)
      if: inputs.cache == 'true' && inputs.registry-url == ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Setup Node.js (with cache and registry)
      if: inputs.cache == 'true' && inputs.registry-url != ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        registry-url: ${{ inputs.registry-url }}

    - name: Setup Node.js (no cache)
      if: inputs.cache != 'true' && inputs.registry-url == ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Node.js (no cache, with registry)
      if: inputs.cache != 'true' && inputs.registry-url != ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        if [ "${{ inputs.frozen }}" = "true" ]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi
