#!/usr/bin/env bash
set -euo pipefail

echo "Bootstrap: starting local dev environment"

# check pnpm
if ! command -v pnpm >/dev/null 2>&1; then
  echo "pnpm not found. Install pnpm (https://pnpm.io/installation)."
  exit 1
fi

ENV_FILE=".env.local"

# Safety check: ensure .env.local is not tracked by git
if [ -f "$ENV_FILE" ] && git ls-files --error-unmatch "$ENV_FILE" >/dev/null 2>&1; then
  echo "⚠️  WARNING: $ENV_FILE is tracked by git! This is a security risk."
  echo "Run: git rm --cached $ENV_FILE"
  exit 1
fi

if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE exists; backing up to $ENV_FILE.bak"
  cp "$ENV_FILE" "$ENV_FILE.bak"
fi

read -r -p "Create .env.local with secure random secrets? [Y/n]: " create
create=${create:-Y}
if [[ "$create" =~ ^(Y|y|)$ ]]; then
  # Generate secure random passwords (using URL-safe base64 to avoid shell special characters)
  POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_')
  MINIO_ROOT_PASSWORD=$(openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_')
  SESSION_SECRET=$(openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_')
  IRON_SESSION_PASSWORD=$(openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_')
  
  cat > "$ENV_FILE" <<EOF
# Local development environment - DO NOT COMMIT
# Generated by scripts/bootstrap_local_dev.sh

# Postgres / DB
POSTGRES_USER=aura_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=aura
DATABASE_URL=postgresql://aura_user:${POSTGRES_PASSWORD}@localhost:5432/aura

# SIWE / auth
NEXT_PUBLIC_APP_NAME=Aura-Sign-Local
SESSION_SECRET=${SESSION_SECRET}
IRON_SESSION_PASSWORD=${IRON_SESSION_PASSWORD}

# Storage (MinIO)
MINIO_ENDPOINT=http://localhost:9000
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}

# Worker / queue
REDIS_URL=redis://localhost:6379

# Optional (embeddings)
EMBEDDING_API=http://localhost:4001
EOF
  echo "✅ Created $ENV_FILE with secure random secrets"
  echo "⚠️  SECURITY: $ENV_FILE contains secrets - it is gitignored and must NEVER be committed!"
fi

echo "Bringing up docker services..."
if [ -f docker-compose.yml ]; then
  # Source .env.local to make environment variables available to docker-compose
  if [ -f "$ENV_FILE" ]; then
    echo "Loading environment variables from $ENV_FILE..."
    set -a
    # shellcheck source=/dev/null
    source "$ENV_FILE"
    set +a
  fi
  docker compose up -d
  echo "Waiting for Postgres..."
  POSTGRES_CONTAINER=""
  for _ in {1..30}; do
    POSTGRES_CONTAINER=$(docker ps -q -f label=com.docker.compose.service=postgres)
    if [ -n "$POSTGRES_CONTAINER" ]; then
      break
    fi
    sleep 1
  done
  
  if [ -z "$POSTGRES_CONTAINER" ]; then
    echo "Warning: Postgres container not found, skipping readiness check"
  else
    until docker exec "$POSTGRES_CONTAINER" pg_isready -U aura_user >/dev/null 2>&1; do
      sleep 1
    done
    echo "Postgres is ready"
  fi
else
  echo "No docker-compose.yml present - skip bringing up infra"
fi

echo "Installing dependencies..."
pnpm install

echo "Generating Prisma client..."
pnpm --filter @aura-sign/database-client prisma generate

echo "Running prisma migrate deploy..."
pnpm --filter @aura-sign/database-client prisma migrate deploy || true

echo "Seeding database..."
pnpm --filter @aura-sign/database-client prisma db seed

echo "Bootstrap complete. Run 'pnpm dev' to start apps."
